[program:botwashapi]
command=/usr/bin/python3 /home/bot/botwashapi.py
directory=/home/bot
autostart=true
autorestart=true
stderr_logfile=/home/bot/botwashapi.err.log
stdout_logfile=/home/bot/botwashapi.out.log
startretries=3
exitcodes=0,2
user=
environment=

eventlistener=slack_alert
